#############################################################################
# Makefile for building: qmlDHTExample
# Generated by qmake (3.1) (Qt 5.10.1)
# Project:  qmlDHTExample.pro
# Template: app
# Command: /opt/qt5pi/sysroot/usr/local/qt5pi/bin/qmake -o Makefile qmlDHTExample.pro -spec devices/linux-rasp-pi3-g++
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = arm-linux-gnueabihf-gcc
CXX           = arm-linux-gnueabihf-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/opt/qt5pi/sysroot -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/opt/qt5pi/sysroot -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I. -I/opt/qt5pi/sysroot/usr/local/qt5pi/include -I/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQuick -I/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui -I/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQml -I/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtNetwork -I/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore -I. -I/opt/qt5pi/sysroot/opt/vc/lib -I/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/linux-rasp-pi3-g++
QMAKE         = /opt/qt5pi/sysroot/usr/local/qt5pi/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/qt5pi/sysroot/usr/local/qt5pi/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/qt5pi/sysroot/usr/local/qt5pi/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qmlDHTExample1.0.0
DISTDIR = /home/ulas/Desktop/asd/qmlDHTExample/.tmp/qmlDHTExample1.0.0
LINK          = arm-linux-gnueabihf-g++
LFLAGS        = -mfloat-abi=hard --sysroot=/opt/qt5pi/sysroot -Wl,-O1 -Wl,-rpath,/usr/local/qt5pi/lib -Wl,-rpath-link,/opt/qt5pi/sysroot/opt/vc/lib -Wl,-rpath-link,/opt/qt5pi/sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link,/opt/qt5pi/sysroot/lib/arm-linux-gnueabihf
LIBS          = $(SUBLIBS) -L=/opt/vc/lib -L/home/ulas/Desktop/asd/qmlDHTExample/ -lwiringPi -lwiringPiDev -L/opt/qt5pi/sysroot/usr/local/qt5pi/lib -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -L/opt/qt5pi/sysroot/usr/lib/arm-linux-gnueabihf -lGLESv2 -lpthread 
AR            = arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_qml.cpp
OBJECTS       = main.o \
		qrc_qml.o
DIST          = /opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/spec_pre.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/unix.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/linux.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/sanitize.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/gcc-base.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/gcc-base-unix.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/g++-base.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/g++-unix.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/qdevice.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/device_config.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/common/linux_device_pre.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/common/linux_device_post.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/common/linux_arm_device_post.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/qconfig.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3drender.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_charts.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_core.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_help.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_location.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_network.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_repparser.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_scxml.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qt_functions.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qt_config.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/linux-rasp-pi3-g++/qmake.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/exclusive_builds.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/toolchain.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/default_pre.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/resolve_config.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/default_post.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/warn_on.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qt.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/resources.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/moc.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/unix/opengl.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/unix/thread.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qmake_use.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/file_copies.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/testcase_targets.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/exceptions.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/yacc.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/lex.prf \
		qmlDHTExample.pro  main.cpp
QMAKE_TARGET  = qmlDHTExample
DESTDIR       = 
TARGET        = qmlDHTExample


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qmlDHTExample.pro /opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/linux-rasp-pi3-g++/qmake.conf /opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/spec_pre.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/unix.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/linux.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/sanitize.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/gcc-base.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/gcc-base-unix.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/g++-base.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/g++-unix.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/qdevice.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/device_config.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/common/linux_device_pre.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/common/linux_device_post.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/common/linux_arm_device_post.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/qconfig.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3drender.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_charts.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_core.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_help.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_location.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_network.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_repparser.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_scxml.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qt_functions.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qt_config.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/linux-rasp-pi3-g++/qmake.conf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/exclusive_builds.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/toolchain.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/default_pre.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/resolve_config.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/default_post.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/warn_on.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qt.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/resources.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/moc.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/unix/opengl.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/unix/thread.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qmake_use.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/file_copies.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/testcase_targets.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/exceptions.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/yacc.prf \
		/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/lex.prf \
		qmlDHTExample.pro \
		qml.qrc \
		/opt/qt5pi/sysroot/usr/local/qt5pi/lib/libQt5Quick.prl \
		/opt/qt5pi/sysroot/usr/local/qt5pi/lib/libQt5Gui.prl \
		/opt/qt5pi/sysroot/usr/local/qt5pi/lib/libQt5Qml.prl \
		/opt/qt5pi/sysroot/usr/local/qt5pi/lib/libQt5Network.prl \
		/opt/qt5pi/sysroot/usr/local/qt5pi/lib/libQt5Core.prl
	$(QMAKE) -o Makefile qmlDHTExample.pro -spec devices/linux-rasp-pi3-g++
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/spec_pre.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/unix.conf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/linux.conf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/sanitize.conf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/gcc-base.conf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/gcc-base-unix.conf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/g++-base.conf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/common/g++-unix.conf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/qdevice.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/device_config.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/common/linux_device_pre.conf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/common/linux_device_post.conf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/common/linux_arm_device_post.conf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/qconfig.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3danimation.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dcore.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dextras.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dinput.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquick.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3drender.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_charts.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_charts_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_core.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_dbus.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_egl_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gamepad.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gui.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_help.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_help_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_kms_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_location.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_location_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimedia.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_network.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_networkauth.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_nfc.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_opengl.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_positioning.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_purchasing.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qml.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quick_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_repparser.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_scxml.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sensors.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialbus.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialport.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sql.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_svg.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_uitools.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_webchannel.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_websockets.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_x11extras.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xml.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/modules/qt_lib_zlib_private.pri:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qt_functions.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qt_config.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/devices/linux-rasp-pi3-g++/qmake.conf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/exclusive_builds.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/toolchain.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/default_pre.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/resolve_config.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/default_post.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/warn_on.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qt.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/resources.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/moc.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/unix/opengl.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/unix/thread.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/qmake_use.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/file_copies.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/testcase_targets.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/exceptions.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/yacc.prf:
/opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/lex.prf:
qmlDHTExample.pro:
qml.qrc:
/opt/qt5pi/sysroot/usr/local/qt5pi/lib/libQt5Quick.prl:
/opt/qt5pi/sysroot/usr/local/qt5pi/lib/libQt5Gui.prl:
/opt/qt5pi/sysroot/usr/local/qt5pi/lib/libQt5Qml.prl:
/opt/qt5pi/sysroot/usr/local/qt5pi/lib/libQt5Network.prl:
/opt/qt5pi/sysroot/usr/local/qt5pi/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile qmlDHTExample.pro -spec devices/linux-rasp-pi3-g++

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		/opt/qt5pi/sysroot/usr/local/qt5pi/bin/rcc \
		main.qml
	/opt/qt5pi/sysroot/usr/local/qt5pi/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/data/dummy.cpp
	arm-linux-gnueabihf-g++ -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/opt/qt5pi/sysroot -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /opt/qt5pi/sysroot/usr/local/qt5pi/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp /opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/QGuiApplication \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qguiapplication.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qtguiglobal.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qglobal.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qconfig.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qtcore-config.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qsystemdetection.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qprocessordetection.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qcompilerdetection.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qtypeinfo.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qsysinfo.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qlogging.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qflags.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qatomic.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qbasicatomic.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qgenericatomic.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qatomic_cxx11.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qatomic_msvc.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qglobalstatic.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qmutex.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qnumeric.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qversiontagging.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qtgui-config.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qcoreapplication.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstring.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qchar.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qbytearray.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qrefcount.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qnamespace.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qarraydata.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringliteral.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringalgorithms.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringview.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringbuilder.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qobject.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qobjectdefs.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qlist.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qalgorithms.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qiterator.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qhashfunctions.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qpair.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qbytearraylist.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringlist.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qregexp.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qstringmatcher.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qcoreevent.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qscopedpointer.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qmetatype.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qvarlengtharray.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qcontainerfwd.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qobject_impl.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qeventloop.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qwindowdefs.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qwindowdefs_win.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qinputmethod.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qlocale.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qvariant.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qmap.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qdebug.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qhash.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qtextstream.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qiodevice.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qvector.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qpoint.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qset.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qcontiguouscache.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qsharedpointer.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qshareddata.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qsize.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQml/QQmlApplicationEngine \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQml/qqmlapplicationengine.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQml/qqmlengine.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qurl.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qurlquery.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQml/qjsengine.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQml/qjsvalue.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQml/qtqmlglobal.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQml/qtqml-config.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtNetwork/qtnetworkglobal.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtNetwork/qtnetwork-config.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQml/qqml.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQml/qqmlprivate.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQml/qqmlparserstatus.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQml/qqmlpropertyvaluesource.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQml/qqmllist.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qmetaobject.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQml/qqmlerror.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQml/qqmldebug.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/QObject \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQuick/QQuickView \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQuick/qquickview.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQuick/qquickwindow.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQuick/qtquickglobal.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQuick/qtquick-config.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQuick/qsgrendererinterface.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQuick/qsgnode.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQuick/qsggeometry.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qopengl.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qt_windows.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qopengles2ext.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qopenglext.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/QRectF \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qrect.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qmargins.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/QMatrix4x4 \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qmatrix4x4.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qvector3d.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qvector4d.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qquaternion.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qgenericmatrix.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qdatastream.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qwindow.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/QEvent \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/QMargins \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/QRect \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qsurface.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qsurfaceformat.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qicon.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpixmap.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpaintdevice.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qcolor.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qrgb.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qrgba64.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qimage.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpixelformat.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qtransform.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qmatrix.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpolygon.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qregion.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qline.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qpainterpath.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qcursor.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qevent.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qkeysequence.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qfile.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qfiledevice.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qvector2d.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qtouchdevice.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQuick/QQuickItem \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQuick/qquickitem.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtQml/qqmlcomponent.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/QList \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qfont.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtGui/qaccessible.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/QTimer \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qtimer.h \
		/opt/qt5pi/sysroot/usr/local/qt5pi/include/QtCore/qbasictimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/qmlDHTExample/bin || mkdir -p $(INSTALL_ROOT)/opt/qmlDHTExample/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/qmlDHTExample/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/qmlDHTExample/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/qmlDHTExample/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/qmlDHTExample/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

